#! /usr/bin/env bash

# Checking config
CONFIG_PATH="$HOME/.config"
DOTMAN_PATH="$HOME/.config/dotman"
DOTMAN_FILE="$HOME/.config/dotman/config.sh"
DOTFILE_PATH=$(cat ${DOTMAN_FILE} | grep path | awk '{print $3}')
if [ ! -d "$DOTMAN_PATH" ]; then
    mkdir -p ${DOTMAN_PATH}
    echo "path = $HOME/dotfiles" > ${DOTMAN_FILE}
fi

# Prompt Variables
option=$1
choice=$(echo $@ | grep -oP "(?<=${option} ).*")

# Main Variables
CONFIG_LIST=$(ls ${DOTFILE_PATH}/.config/${PKGS})

function set() {
    if [ -z "$choice" ]; then
        echo "Usage: dotman set </path/to/your/dotfiles>"
    elif [[ "$choice" = . ]]; then
        rn=$(pwd)
        echo "path = $rn" > $DOTMAN_FILE
        if [ $? -eq 0 ]; then
            echo "Dotfiles path changed to '$rn'"
        else
            echo "Failed to change the path"
        fi
    else
        echo "path = $choice" > $DOTMAN_FILE
        if [ $? -eq 0 ]; then
            echo "Dotfiles path changed to '$choice'"
        else
            echo "Failed to change the path"
        fi
    fi
}

function remove() {
    echo ":: Processing dotfiles changes..."
    totalnumber=0
    number=1
    for PKGS in ${choice[@]}; do
        totalnumber=$(($totalnumber + 1))
    done
    for PKGS in ${choice[@]}; do
        if [ "$CONFIG_LIST" ]; then
            rm -rf ${DOTFILE_PATH}/.config/${PKGS}
            if [ $? -eq 0 ]; then
                echo "($number/$totalnumber) $PKGS has been removed from dotfiles"
            else
                echo "($number/$totalnumber) failed to remove $PKGS from dotfiles"
            fi
        else
            echo "there's no folder nor files named $PKGS in the dotfiles."
        fi
        number=$(($number + 1))
    done
}

function sync() {
    echo ":: retrieving configurations..."
    totalnumber=0
    number=1
    for PKGS in ${choice[@]}; do
        totalnumber=$(($totalnumber + 1))
    done
    for PKGS in ${choice[@]}; do
        if [ "$(ls ${DOTFILE_PATH}/.config/$PKGS &>/dev/null)" ]; then remove &>/dev/null; fi

        if [ -d "${CONFIG_PATH}/${PKGS}" ]; then mkdir -p ${DOTFILE_PATH}/.config/${PKGS}; fi
        cp -rf ${CONFIG_PATH}/$PKGS ${DOTFILE_PATH}/.config
        if [ $? -eq 0 ]; then
            echo "(${number}/${totalnumber}) $PKGS succesfully copied into dotfiles"
        else
            echo "(${number}/${totalnumber}) failed to copy $PKGS into the dotfiles"
        fi
        number=$(($number + 1))
    done

}

function syncall() {
    echo ":: Synchronizing dotfiles with the configs..."
    echo ":: Starting full dotfiles update..."
    echo "checking the dotfiles..."
    echo "looking for conflicting configs..."
    echo ""
    rm -rf /tmp/syncall &>/dev/null
    for PKGS in $(command ls ${DOTFILE_PATH}/.config); do
        size=$(du -sh ${CONFIG_PATH}/$PKGS | awk '{print $1}')
        dotfilesize=$(du -sh $DOTFILE_PATH | awk '{print $1}')
        number=$(($number + 1))
        echo $PKGS >> /tmp/syncall
    done
    echo "Packages: (${number}) $(echo $(cat /tmp/syncall))"
    echo ""
    echo "Current Dotfiles Size: $dotfilesize"
    echo ""
    echo -n ":: Proceed to Sync All? it'll overwrite modified configs! [Y/n] "
    read answer
    case $answer in 
        [yY]) confirm="yes" ;; 
        [nN]) confirm="no" ;; 
        *) confirm="yes" ;; 
    esac

    if [ "$confirm" = yes ]; then
        echo ":: Retrieving configs..."
        totalnumber=0
        number=1
        for PKGS in $(command ls ${DOTFILE_PATH}/.config); do
            totalnumber=$(($totalnumber + 1))
        done
        for PKGS in $(command ls ${DOTFILE_PATH}/.config); do
            rm -rf ${DOTFILE_PATH}/.config/${PKGS} && \
            if [ -d "${CONFIG_PATH}/${PKGS}" ]; then mkdir -p ${DOTFILE_PATH}/.config/${PKGS}; fi
            cp -rf ${CONFIG_PATH}/$PKGS ${DOTFILE_PATH}/.config/
            if [ $? -eq 0 ]; then
                echo "($number/$totalnumber) succesfully updated $PKGS"
            else
                echo "($number/$totalnumber) failed to update da $PKGS"
            fi
            number=$(($number + 1))
        done
    else
        echo "Process cancelled"
    fi
}

function list() {
    JARAK=30
    BLUE="\033[0;34m"
    BLACK="\033[0;30m"
    NONE="\033[0m"
    printf "${BLACK}##${NONE}[${BLUE}List Of Configuration${NONE}]\n"
    for list in $(ls ${DOTFILE_PATH}/.config); do
        if [ -d "${DOTFILE_PATH}/.config/$list" ]; then
                printf "${BLACK}-- ${BLUE} "
                printf "$(printf "%-${JARAK}s" "$list")${NONE}\n"
        elif [ -f "${DOTFILE_PATH}/.config/$list" ]; then
                printf "${BLACK}-- ${NONE} "
                printf "$(printf "%-${JARAK}s" "$list")\n"
        else
            echo "there's nothing in your dotfiles($dotfile_path)."
        fi
    done
}

function confirmation() {
    if [ -n "$choice" ]; then
        number=0
        case $thingstodo in
            remove) 
                echo "checking the dotfiles..."
                echo ""
                for PKGS in ${choice[@]}; do
                    size=$(du -sh ${DOTFILE_PATH}/.config/$PKGS | awk '{print $1}')
                    number=$(($number + 1))
                done
                echo "Packages (${number}) $choice"
                echo ""
                echo "Total Removed Size: $size"
                echo ""
                echo -n ":: Are you sure to remove ($choice) from dotfiles? [Y/n] " 
                ;;
            sync) 
                echo "checking the dotfiles..."
                echo "looking for conflicting packages..."
                for PKGS in ${choice[@]}; do
                    size=$(du -sh ${CONFIG_PATH}/$PKGS | awk '{print $1}')
                    dotfilesize=$(du -sh $DOTFILE_PATH | awk '{print $1}')
                    if $(ls ${DOTFILE_PATH}/.config/$PKGS &>/dev/null); then 
                        echo "warning: $PKGS already in the dotfiles -- overwriting"
                    fi
                    number=$(($number + 1))
                done
                echo ""
                echo "Packages (${number}) $choice"
                echo ""
                echo "Package Configs Size: $size"
                echo "Current Dotfiles Size: $dotfilesize"
                echo ""
                echo -n ":: Proceed to sync [Y/n] " 
                ;;
        esac
        read answer
        case $answer in
            [yY]) confirm="yes" ;;
            [nN]) confirm="no" ;;
            *) confirm="yes" ;;
        esac
    else
        echo "Please input the package name!"
    fi
}

function help() {
echo "usage:  dotman <operation> [...]
operations:
    dotman {-h --help help}
    dotman {-l --list list}
    dotman {--set set}          <path for dotfiles>
    dotman {-R --remove remove} <package(s)>
    dotman {-S --sync sync}     <package(s)>
    dotman {-Syu --syncall syncall}

use 'dotman {-h --help help}' to show this page"
}

# Run it!
if [ -n "$option" ]; then
    case $option in
        --set|set) set ;;
        -[rR]|-[rR][mM]|--remove|remove) thingstodo="remove"; confirmation; if [ "$confirm" = yes ]; then remove; fi ;;
        -[sS]|--sync|sync) thingstodo="sync"; confirmation; if [ "$confirm" = yes ]; then sync; fi ;;
        -[sS][yY][uU]|-[sS][yY]|-[sS][uU]|--syncall|syncall) syncall ;;
        -[lL]|--list|list) list ;;
        -[hH]|--help|help) help ;;
        *) echo "wrong input (use 'dotman help' for help)" ;;
    esac
else
    echo "no operation specified (use 'dotman help' for help)"
fi
